# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b24c5610b935ee9f128914cfe0c68b60302bce36759cc1778f68c30d66ff0e7caa924ba60baf72fcfc5f21f870ecfa11c52ded5fa94e903cc45f44b9d6d7085

test:
  secret_key_base: 3333fe2a4eeb0ab3cc03c20c557aee45805e4f83afc6becaa2fa3244ebe557d6182469867744e0bd6bfa46058f6b5bc48fe2ead1b3532e5af7931da1dace4244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
